version: '3'
services:
  mqtt-wire:
    image: mqtt-wire
    container_name: mqtt-wire-noti
    ports:
      - "8080:8080"
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: always
    volumes:
      - ./mosquitto/:/mosquitto/:rw
    ports:
      - "1883:1883"
      - "9001:9001"

  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      - REDIS_PASSWORD=manage
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  n8n:
    image: n8nio/n8n
    restart: always
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=manage
    ports:
      - 5678:5678
    volumes:
      - ~/.n8n:/home/node/.n8n
    # Wait 5 seconds to start n8n to make sure that PostgreSQL is ready
    # when n8n tries to connect to it
    command: /bin/sh -c "sleep 5; n8n start"
volumes:
  redis_data:
    driver: local
